### ISSUE TITLE
Header row is not up to par with modern web standards, it requires review...

### ISSUE THREAD

**Issue by penkar** [paul-tqh-nguyen/arxiv_as_a_newspaper#37]
Consider checking the width of the page each time you refresh the header, then counting the characters in the article title, and only displaying full titles rather than... cutting off articles that are equally important if not more important than their preceding peers. Come on this is 2019!

**Comment by paul-tqh-nguyen** [comment]
https://github.com/paul-tqh-nguyen/arxiv_as_a_newspaper/commit/ae57eb7a869c1367c83c919ca8bc6a5aaf6e2c06 @penkar , let me know if this addresses your needs.
