### ISSUE TITLE
Update favicon

### ISSUE THREAD

**Issue by penkar** [paul-tqh-nguyen/arxiv_as_a_newspaper#38]
You should consider doing your readers a favor and updating your favicon. The red color used doesn't fit with your page's style, and the text in the middle is too small to make out. Consider a simple less detailed icon, or a single letter. If you're important a single letter is all you need.

**Comment by paul-tqh-nguyen** [comment]
@penkar , let me know if the changes at https://github.com/paul-tqh-nguyen/arxiv_as_a_newspaper/commit/6b12c2678cde1db05966fecd8c44bffea9379b94 meet your needs.
