### ISSUE TITLE
Loading Animation

### ISSUE THREAD

**Issue by penkar** [paul-tqh-nguyen/arxiv_as_a_newspaper#53]
It might be useful to not render the loading animation when the loading has finished, and just have it on the page when needed.

**Comment by paul-tqh-nguyen** [comment]
https://github.com/paul-tqh-nguyen/arxiv_as_a_newspaper/commit/cb6326599a27790c9e73f68131e834730ddbb178 

This patch makes it so that we no longer render the loading screen after the content has been loaded.
