### ISSUE TITLE
Currently 1 result is cutoff in the menu.

### ISSUE THREAD

**Issue by penkar** [paul-tqh-nguyen/arxiv_as_a_newspaper#58]
.side-navigation-bar needs: **height: calc(100% - 48px);**

Also, the menu area background color might differ slightly from the header background color.

**Comment by paul-tqh-nguyen** [comment]
https://github.com/paul-tqh-nguyen/arxiv_as_a_newspaper/commit/dca6e45c56044cd5860476cc2b168b1c628507e5

This fixes it. We now see all the research fields in the navigation bar.
