### ISSUE TITLE
When you switch topics the header items shift

### ISSUE THREAD

**Issue by penkar** [paul-tqh-nguyen/arxiv_as_a_newspaper#59]
This could be fixed by adding **body {
overflow-y: scroll;
}**
There are many options available.

**Comment by paul-tqh-nguyen** [comment]
https://github.com/paul-tqh-nguyen/arxiv_as_a_newspaper/commit/b18ca379014289814d63426573366879643e68b6

This patch goes the route of least resistance by adding a permanent scroll bar.

**Comment by paul-tqh-nguyen** [comment]
This actually causes problems with center-alignment of certain text. Reopening to address this issue.

**Comment by paul-tqh-nguyen** [comment]
Oops, that comment was actually regarding #54; closing again.
